export type JobItem = {
  id: number;
  title: string;
  company: string;
  location_countries: string;
  location_states: string;
  location_cities: string;
  text_description: string;
  apply_start: string;
  expiration_date: string;
  salary_type_name: string;
  remote: number;
  accepts_opt_cpt_candidates: number;
  willing_to_sponsor_candidate: number;
  work_auth_required: number;
  applied_count: number;
  oa_count: number;
  behavior_interview_count: number;
  technical_interview_count: number;
  rejected_count: number;
  offered_count: number;
  tag_list: string;
};
